### ISSUE TITLE
1.0 milestone

### ISSUE THREAD

**Issue by gfontenot** [antitypical/Result#101]
I feel like we're waffling around a bit, and it'd be great to push a 1.0 release soon. Given that we have a brief window of Swift source stability before it breaks again, seems like we might want to do that sooner rather than later. Are there specific things that we want to have in place before cutting a 1.0 release?

**Comment by robrix** [comment]
- #6 / #93

**Comment by davideme** [comment]
#6 and #93 are closed and merge, what are the blockers ? If need any help, tell us.

**Comment by neilpa** [comment]
Can we steal a contributing from RAC, Argo, etc? (but I'm for tagging a 1.0 without it).

**Comment by robrix** [comment]
I think we can and should.

**Comment by gfontenot** [comment]
#3 is done. Is there anything holding us back now? Can we just draw a line and ship 1.0?

**Comment by neilpa** [comment]
I'm in favor of that

**Comment by ishkawa** [comment]
> Can we just draw a line and ship 1.0?

+1. Thank you for leading this!

**Comment by gfontenot** [comment]
@robrix Does this make sense to you? I can push it all now if so.

**Comment by gfontenot** [comment]
Pushing 1.0 now

**Comment by robrix** [comment]
@gfontenot: Sorry for my radio silence! Yes, all of this makes sense. Thanks for releasing!

I apologize for my absenteeism, as I know it can be inconvenient; but please know that it is, above all, an indication of my confidence in how everyone in @antitypical/result will treat the framework. I’m very glad you’re all involved :gift_heart:

Great work, everyone; thank you very much :clap:
