### ISSUE TITLE
Cannot build Result 0.4.5 with Carthage 0.9.3 and XCode 6.4

### ISSUE THREAD

**Issue by guidomb** [antitypical/Result#103]
I was trying to work on proyects that require XCode 6.4 and when executing `carthage update --platform ios` I get the following error with result.

```
carthage update --platform ios
*** Cloning ReactiveCocoa
*** Cloning Result
*** Cloning Box
*** Checking out Result at "0.4.5"
*** Downloading Box.framework binary at "1.2.2"
*** Downloading ReactiveCocoa.framework binary at "v3.0"
*** xcodebuild output can be found in /var/folders/gf/dslbq4t94zg44sz7wnk2lg2r0000gp/T/carthage-xcodebuild.YvCHnr.log
A shell task failed with exit code 66:
xcodebuild: error: Scheme Result-watchOS is not currently configured for the build action.
```

## Cartfile ##

```
github "ReactiveCocoa/ReactiveCocoa" ~> 3.0.0
```

## Cartfile.resolved ##

```
github "robrix/Box" "1.2.2"
github "antitypical/Result" "0.4.5"
github "ReactiveCocoa/ReactiveCocoa" "v3.0.0"
```

Is this a Result issue or a Carthage issue?

**Comment by mdiep** [comment]
Which version of Carthage are you using? Some Xcode lols resulted in some misidentification issues with the new platforms.

**Comment by guidomb** [comment]
I am using Carthage `0.9.3`

**Comment by gfontenot** [comment]
@guidomb Is this still happening?

**Comment by guidomb** [comment]
To be honest I am not using any of this versions anymore. As far as I can tell this is not happening in Carthage 0.10.0 with XCode 7.1.1 and Result > 0.6.0

**Comment by robrix** [comment]
Thanks for the update. I’m going to close this out now.
