### ISSUE TITLE
Can't submit build with XCode 7.1 with Result beta tags.

### ISSUE THREAD

**Issue by jamesdo** [antitypical/Result#107]
Just updated to 7.1, and submitting to the app store is failing due to non integer values being in the tag of Result. I also can't seem to point my Podfile to the most recent non beta release.
![screen shot 2015-10-23 at 5 17 22 pm](https://cloud.githubusercontent.com/assets/5696001/10705155/f931e440-79a9-11e5-9233-c9b9ac7f1a31.png)

**Comment by NachoSoto** [comment]
This seems to be something of `CocoaPods` doing. `CFBundleShortVersionString` is not actually changed to match the release version (because why would it?):
https://github.com/antitypical/Result/blob/master/Result/Info.plist#L18

**Comment by jamesdo** [comment]
With the update to XCode this past week, it seems that if you're using Swift 2.1, and you're pulling Result from Cocoapods, that the tag from your repo for your Swift 2.0+ releases that all include the word beta will break the build.

**Comment by ikesyo** [comment]
Closing this since it is a CocoaPods issue. Please check https://github.com/CocoaPods/CocoaPods/issues/4421 and https://github.com/CocoaPods/CocoaPods/pull/4444.
