### ISSUE TITLE
Type alias result without committing to an error type

### ISSUE THREAD

**Issue by yoavschwartz** [antitypical/Result#109]
I would like to do something in the lines of the following:
typealias OperationResult = Result<valuetype> and just have any ErrorType as the error type. 
But as it is now I have to declare a concrete ErrorType Result<valuetype, NSError>
Which means I can't use the feature of swift where every enum can just be an ErrorType. I have to use NSError only. Any workarounds?

**Comment by robrix** [comment]
Possibly `Result<ErrorType, …>`?

**Comment by yoavschwartz** [comment]
You get an "Expected type" error.

**Comment by robrix** [comment]
Got my parameters the wrong way around. If your operations produce strings, then:

```swift
typealias OperationResult = Result<String, ErrorType>
```

would work, except:

```
boom.swift:16:29: error: using 'ErrorType' as a concrete type conforming to protocol 'ErrorType' is not supported
typealias OperationResult = Result<String, ErrorType>
                            ^
```

Maybe we should stop constraining `Result`’s `Error` type parameter to `ErrorType`?

**Comment by yoavschwartz** [comment]
Hmmm, in my own private implementation I had something in the lines of:
```swift
Result<T>
case Success<T>
case Error <ErrorType>
```
So this one essentially does the same but you don't have to commit to a specific concrete ErrorType. I think it's more swift-y to say put whatever you want as long as it conforms to ErrorType.

**Comment by neilpa** [comment]
> Maybe we should stop constraining Result’s Error type parameter to ErrorType?

This would break all of the `throws` methods defined in `Result`.

> So this one essentially does the same but you don't have to commit to a specific concrete ErrorType. I think it's more swift-y to say put whatever you want as long as it conforms to ErrorType.

This defeats one of the main benefits of `Result` which is compile-time error checking

**Comment by robrix** [comment]
> This would break all of the `throws` methods defined in `Result`.

Ah, of course.

> > So this one essentially does the same but you don't have to commit to a specific concrete ErrorType. I think it's more swift-y to say put whatever you want as long as it conforms to ErrorType.
> 
> This defeats one of the main benefits of `Result` which is compile-time error checking

Agreed. I want Swift to declare concrete error types, not to elide them from `Result`.

**Comment by yoavschwartz** [comment]
> This defeats one of the main benefits of Result which is compile-time error checking
What advantages do you get from have the type `Result<type, NSError>` as oppose to Result<type, ErrorType> ?

> Agreed. I want Swift to declare concrete error types, not to elide them from Result.
Swift's design already made the choice of not declaring concrete error type in the `throws` and in fact when you use `throws` in the `Result` you lose that information. Otherwise you would write `foo() throws CBError` or something in the sorts. In all honesty the fact that you have to choose a concrete type at definition is probably a swift error. There is no reason you shouldn't be able to repass ErrorType as a type for your error.

**Comment by Thomvis** [comment]
@yoavschwartz you could create your own enum and then make it conform to `ResultType`. That will give you most functionality of `Result` (e.g. `map`, `flatMap`) just by implementing a few basic methods on your own type. It might not be a complete solution (we could make it more compelling by moving more functionality from `Result` to `ResultType`), but perhaps an interesting one to try out.

**Comment by yoavschwartz** [comment]
@Thomvis It's actually what I am already doing ;) I just thought the Result type itself makes more sense when defined by one type and wanted to discuss the pro's and con's like we did here. I am satisfied that there are compelling arguments for both types and you have done great work with the code you wrote. It comes down to design choices. I tried to come up with a way to support both types but you can't overload an Enum.

**Comment by robrix** [comment]
With that, I’m going to close this out, as there doesn’t seem to be any action to be taken. Thanks for an interesting discussion, all!
