### ISSUE TITLE
Cannot use auto closure init in a closure

### ISSUE THREAD

**Issue by frogcjn** [antitypical/Result#119]
for example:
```swift
func(){
let result: Result<String, NSError> = Result(try tryIsSuccess("success")) //This is OK in function
}

let simpleBlock: ()->Void =  {
let result: Result<String, NSError> = Result(try tryIsSuccess("success")) //This is not OK in colure
}
simpleBlock()
```

So my suggestion is to add a init version without @autoclosure mark
```swift
extension Result{
    public init(_ f: () throws -> T) {
        self.init(try f())
    }
}
```

**Comment by robrix** [comment]
Curious. What error does `swiftc` give you?

**Comment by frogcjn** [comment]
it shows me that simpleBlock should be marked with "throws"

**Comment by ishkawa** [comment]
Looks like a bug of Swift compiler, because `simpleBlock` below is inferred as `() throws -> Void` in spite of that `try tryIsSuccess("success")` is inside the auto closure and `Result(_:)` never throws errors.

```swift
func simpleFunc() {
	let result: Result<String, NSError> = Result(try tryIsSuccess("success"))
}

// simpleBlock is inferred as `() throws -> Void`.
let simpleBlock = {
	let result: Result<String, NSError> = Result(try tryIsSuccess("success"))
}
```

I found the radar that points out the same bug.
https://openradar.appspot.com/22437049

**Comment by frogcjn** [comment]
Yes. It's a Swift compiler bug.
But I think the non-autoclusure version init is also necessary.
for example, this is my code to use the non-autoclusure version init of Result:
            let result = Result{ [weak asset] in
                guard let asset = asset else { throw Break.Unknown }
                for key in keys {
                    var error: NSError?
                    switch asset.statusOfValueForKey(key, error: &error) {
                    case .Failed   : throw Break.Error(error!)
                    case .Cancelled: return nil
                    case .Loaded   : continue
                    default        : throw Break.Unknown
                    }
                }
                return asset.playable && !asset.hasProtectedContent
            }

**Comment by robrix** [comment]
I’m :+1: to adding a non-`@autoclosure` variant as you suggest. Would you be willing to submit a PR?
