### ISSUE TITLE
watchOS deployment target

### ISSUE THREAD

**Issue by AquaGeek** [antitypical/Result#128]
I'm seeing linker failures when using Carthage to install ReactiveCocoa, because this project doesn't have a watchOS deployment target set. Xcode 7.2 (released this week) includes watchOS 2.1, so that becomes the new default for this project. This leads to issues with projects that have an earlier target set (e.g. ReactiveCocoa targets 2.0).

Are there any objections to me opening a pull that adds that build setting?

**Comment by Thomvis** [comment]
This has just been merged in as per https://github.com/antitypical/Result/pull/127. I think @NachoSoto is preparing a new release.

**Comment by NachoSoto** [comment]
[`v1.0.1`](https://github.com/antitypical/Result/releases/tag/1.0.1) is out! :)

**Comment by AquaGeek** [comment]
:trophy: Thank you!
