### ISSUE TITLE
RFC: Add NoError type

### ISSUE THREAD

**Issue by NachoSoto** [antitypical/Result#130]
```swift
enum NoError: ErrorType { }
```
As mentioned in [`Commandant`](https://github.com/Carthage/Commandant/pull/41/files#r47448896), I think it would be a good idea to put this type in `Result` so that `ReactiveCocoa`, `Commandant`, and other frameworks can take advantage of it.

**Comment by kylef** [comment]
I'm slightly confused with this one without knowledge of Commandant, does `NoError` represent there wasn't an error at all? If so, what benefits would there be a result instead of just returning the success type?

**Comment by mdiep** [comment]
:+1: 

> I'm slightly confused with this one without knowledge of Commandant, does NoError represent there wasn't an error at all?

It represents that an error isn't possible.

> If so, what benefits would there be a result instead of just returning the success type?

It's useful for using APIs can cope with errors. In ReactiveCocoa's case, most signals can send an error. But in some cases, a signal can't error.

Likewise, you might return a generic `Result` from your API and let the consumer specify the error type. But the consumer can choose `NoError` if they can guarantee that an error can't be created.

**Comment by kylef** [comment]
Thanks @mdiep :+1:

**Comment by Thomvis** [comment]
I'd also like a NoError type. (Like Commandant, I currently have [my own](https://github.com/Thomvis/BrightFutures/blob/master/BrightFutures/Errors.swift#L27))

**Comment by robrix** [comment]
:+1: — good call @NachoSoto.

**Comment by robrix** [comment]
Incidentally: I dig the RFCs!

Just so’s not to discourage anybody from trying their idea out in code, I’d be :+1: to RFCs submitted as PRs as well. Whichever works best for the author, really :heart:

**Comment by NachoSoto** [comment]
+1

In this case it's so simple than the snippet in the issue covers it :P but I'll make an actual PR now that I've heard enough :+1: :)
