### ISSUE TITLE
RFC: Drop the ErrorType constraint

### ISSUE THREAD

**Issue by Thomvis** [antitypical/Result#131]
I'm not sure what constraining the second generic placeholder to `ErrorType`gives us. IIRC this has come up during discussions on other issues as well.

If there is stuff that only works on `ErrorType`s we can always add that to a protocol extension like so:

```swift
extension ResultType where Error: ErrorType { }
```

**Comment by NachoSoto** [comment]
It's just semantically more correct, otherwise you'd be talking about `Either`.

If only we could do `typealias Result<T, E: ErrorType> = Either<T, E>`.

**Comment by robrix** [comment]
I’m not sure. A library might reasonably want to produce `Result<A, String>` without exporting `String : ErrorType`.

**Comment by mdiep** [comment]
I'd be interested in seeing what this does to the code.

**Comment by gfontenot** [comment]
So this would mean moving `dematerialize` to `ResultType`, which I guess is fine, but would it be confusing for that to not exist sometimes?

**Comment by gfontenot** [comment]
As far as I can tell, that'd be the only significant change to the API, if that helps the discussion here. I believe that constraint was added in order to support that specific transformation.

**Comment by neilpa** [comment]
What's the motivation for removing it? It's trivial to create enums (or other types) conforming to `ErrorType` that provide stronger static guarantees that are lost if the constraint's removed.

> I’m not sure. A library might reasonably want to produce Result<A, String> without exporting String : ErrorType.

But now consumers are in the business of having to parse strings to figure out what actually went wrong. This feels like a step backwards.

**Comment by Thomvis** [comment]
I agree that people should probably use errors that conform to ErrorType. I'm not sure if we should make it impossible to use anything else (e.g. Strings or ints).

The motivation to propose this was mainly because I didn't see any drawbacks to dropping the constraint, but did see merit in leaving it open.

I wouldn't mind making a PR to see how this plays out in code.

**Comment by robrix** [comment]
> But now consumers are in the business of having to parse strings to figure out what actually went wrong. This feels like a step backwards.

But that’s consumers’ business, right?

Prescriptivism here arguably helps push people in the right direction (tho I fear we’d mostly annoy them) but it could also limit our utility for use cases we haven’t considered.

**Comment by NachoSoto** [comment]
> The motivation to propose this was mainly because I didn't see any drawbacks to dropping the constraint, but did see merit in leaving it open.

Like @neilpa said, it would provide weaker static guarantees.

To be fair, obviously `Etiher<L, R>` is just as valuable, but it represents something completely different.

**Comment by neilpa** [comment]
>> But now consumers are in the business of having to parse strings to figure out what actually went wrong. This feels like a step backwards.

> But that’s consumers’ business, right?

I meant the downstream consumer of some theoretical library returning `Result<T, String>`. They're now in the unfortunate position of parsing error strings (or more likely just ignoring them).

More pragmatically, this would be a breaking change requiring a major version bump. Even if I were in favor of this change, the lack of concrete examples makes it hard to justify this change. Especially considering the number of large projects with a base dependency on `Result`.

**Comment by neilpa** [comment]
Actually, I don't think it technically requires a major version bump but still feels like it's in murky water in that regard.

**Comment by gfontenot** [comment]
> I don't think it technically requires a major version bump but still feels like it's in murky water in that regard.

I think it _would_ constitute a major version bump because consumer code might be relying on the fact that `Error` currently conforms to `ErrorType`. For example, people could be using the `as NSError` conversion that comes for free from `ErrorType`. This code would break and users would need to add constraints on their end.

I don't mind if we jump straight to 2.0 (we have too much ceremony about this stuff in our community), and I'm not super tied to the constraint itself. I've always appreciated that `Result` was just a more semantic `Either` anyway.

All in all, I'm not sure that I have a strong opinion one way or another. I _might_ lean towards removing the constraint and moving things like `dematerialize` to `ResultType` if I had to chose.

**Comment by NachoSoto** [comment]
My biggest reason against this is that the type would no longer be a `Result`, but something more like `Either`.

**Comment by neilpa** [comment]
> I don't mind if we jump straight to 2.0 (we have too much ceremony about this stuff in our community)

That's fine, but I think the bar should be higher for something that's at the bottom of the dependency graph for so many projects.

> My biggest reason against this is that the type would no longer be a Result, but something more like Either.

:+1:. If you want an `Either` type just use that.

**Comment by NachoSoto** [comment]
Like I said, if we could implement most of the functionality of `Result` in an `Either`, and things like `dematerialize` in a constrained extension, **AND** define a `typealias` for `Result` `where Error: ErrorType`, I'd be :+1: for this change, but given that we can't do the last part I'm not really in favor of this as part of this framework.

**Comment by robrix** [comment]
Okay, I think we have enough to decide against this. @Thomvis, any objections to closing this out?

**Comment by robrix** [comment]
Whoops, meant to say that _before_ closing it! My apologies.

**Comment by Thomvis** [comment]
I agree that the implementation as described by @NachoSoto is the ideal solution, but we'll have to wait for Swift 3/4 for that. 

One last argument and then I'll stop, because I don't mean to drag this along. The constraint on ErrorType was added last June (after the introduction of Swift 2, https://github.com/antitypical/Result/commit/06456d029477253f5fab695b7c03662535e41fd5). I remember using Result before that and I think it was a great type nonetheless. At the same time, I think a hypothetical Result type in the Swift stdlib would probably have the ErrorType constraint. So it kind of depends on what we want Result to be: the best Swift citizen or a (slightly) more versatile tool.

If there's still disagreement, feel free to close this issue at any time.

**Comment by Thomvis** [comment]
`Either` way, thanks for the interesting discussion!
