### ISSUE TITLE
Push 1.0.2 to CocoaPods Trunk

### ISSUE THREAD

**Issue by ashfurrow** [antitypical/Result#136]
Hey there! I noticed after @mdiep bumped the podspec to 1.0.2, it didn't get pushed to trunk. Would someone be able to do that? Then we can [push ReactiveCocoa 4.0.1](https://github.com/mhuusko5/Podspecs/pull/8).

**Comment by bjarkehs** [comment]
:+1:

**Comment by robrix** [comment]
@ashfurrow: :+1:

I don’t really follow the cocoapods stuff & don’t have the bandwidth to jump into it at the moment, but I’ve invited you to the team so you can do that directly if you’d like. Don’t sweat it if you don’t have the bandwidth either; empowerment, rather than obligation :smile:

**Comment by kylef** [comment]
https://github.com/CocoaPods/Specs/commit/c3d5bcd2eeea1e7d3154d3e773328aadd95ae80d

**Comment by robrix** [comment]
:bow: thanks @kylef!

**Comment by ashfurrow** [comment]
Super, thanks! It looks like the team is doing a good job with the podspec, it just needed to be pushed. I'm happy to help out. @kylef would you add me as an owner to the pod on Trunk?
