### ISSUE TITLE
swift 2.2 warnings

### ISSUE THREAD

**Issue by paulz** [antitypical/Result#142]
Thank you for the awesome Pod!

We have migrated to swift 2.2 and xcode7.3 and started to get these warnings:

⚠️  Pods/Result/Result/Result.swift:182:89: __LINE__ is deprecated and will be removed in Swift 3, please use #line

public func `try`(function: String = __FUNCTION__, file: String = __FILE__, line: Int = __LINE__, `try`: NSErrorPointer -> Bool) -> Result<(), NSError> {
                                                                                        ^~~~~~~~

⚠️  Pods/Result/Result/ResultType.swift:5:2: use of 'typealias' to declare associated types is deprecated; use 'associatedtype' instead

        typealias Value
        ^~~~~~~~~

Unfortunately for us, they are repeated by compiler so many times that our [travis-ci.com](http://travis-ci.com) build log runs out of the limit and cause build failure.

Would it be possible to update Result to latest Swift and Xcode?

Thank you!

**Comment by ikesyo** [comment]
This is already captured in #138. Closing this.
