### ISSUE TITLE
New Tag containing #141

### ISSUE THREAD

**Issue by norio-nomura** [antitypical/Result#145]
I want to tag containing #141.
Which version should we use?
- 1.0.3
- 1.1.0
- 2.0.0 https://github.com/antitypical/Result/pull/138#issuecomment-200134995

**Comment by mdiep** [comment]
:+1: 2.0.0

**Comment by robrix** [comment]
:+1:

**Comment by norio-nomura** [comment]
Thanks for replying.
I added https://github.com/antitypical/Result/releases/tag/2.0.0
I'm not good at english. If description is wrong, please fix that. :bow:
