### ISSUE TITLE
ResultResult syntax unclear (or not compiling)

### ISSUE THREAD

**Issue by kristofvanlandschoot** [antitypical/Result#155]
Does anybody know what is wrong with this? I can't seem to get ResultResult workaround to compile. Latest Xcode (version 7.3), latest Result (version 2.0.0)

![](https://dropblets.s3-eu-central-1.amazonaws.com/Screen-Shot-2016-04-19-23-50-37-tj0gULjCqpEj7V4yr42DB.png)

Probably I'm missing something in the syntax. Any help appreciated!

**Comment by mdiep** [comment]
I think you need to write `ResultResult<Int,NSError>.t`. (Notice the `.t` at the end.)

**Comment by kristofvanlandschoot** [comment]
duh! Thanks.
