### ISSUE TITLE
Namespace qualify Result

### ISSUE THREAD

**Issue by startupthekid** [antitypical/Result#159]
In the case where we want to use the `Result` type and import other libraries that have their own `Result` class, how can we properly qualify this library by it's namespace?

For example, if I want to use `Result<Int, NSError>` and in the same file, import Alamofire (which has it's own `Result` type), how can I qualify the name space?

Example:

```swift
import Result
// all good here
func myFunc() -> Result<Void, NSError> {

}

------------------------------
import Result
import Alamofire
func myFunc() -> Result<Void, NSError> {

}
```

In the second example, the compiler complains of an unambiguous reference, which makes sense but you can't do `Result.Result<Void, NoError>` because then the compiler complains that it's missing generic arguments.

**Comment by mdiep** [comment]
There's a workaround listed in #77.
