### ISSUE TITLE
minor release (2.0.1?)

### ISSUE THREAD

**Issue by dileping** [antitypical/Result#161]
Hey guys,

could you make a minor release, like 2.0.1 or something, to maintain compatibility with most recent swift versions. As I checked, current ```master``` works fine with it both on Mac and Linux.

Will appreciate it a lot!

Thanks,
Daniel

**Comment by mdiep** [comment]
I'll try to do this in the next day or two. It'll probably be 2.1 because of #153.

**Comment by mdiep** [comment]
https://github.com/antitypical/Result/releases/tag/2.1.0 🎉

**Comment by dileping** [comment]
@mdiep Thanks a lot! I really appreciate it!
