### ISSUE TITLE
Dropping Swift 2.x supports

### ISSUE THREAD

**Issue by norio-nomura** [antitypical/Result#166]
I experienced difficulty with using master branch of antitypical/Result from Swift 3 migrated project.
Most of projects are using xcworkspace and Xcode 8 does not provide overriding configuration of referencing projects.
`SWIFT_VERSION = 2.3` is applied on project, but not workspace.

I think that we need swift-3 only branch of Result for resolving that.
So, I created swift-3 branch on my fork and dropped Swift 2.x supports on that.
https://github.com/norio-nomura/Result/tree/swift-3
I also changed some naming to conforming Swift 3.0 API guidelines on that.

@antitypical/result: How do you think about this?

**Comment by mdiep** [comment]
Since Result has a release that supports Swift 2.3 / Xcode 8, I think we can adopt Swift 3 on `master` and start releasing alpha versions of Result 3.

**Comment by NachoSoto** [comment]
I'm :+1: with that.

**Comment by norio-nomura** [comment]
Thanks! I opened #167.
