### ISSUE TITLE
Installation section

### ISSUE THREAD

**Issue by lfarah** [antitypical/Result#170]
What do you think about a ```Installation Section```?
I created an [iOS Readme Template](https://github.com/awesome-labs/iOS-readme-template) and that's how we created an Installation. What do you think about doing this for *Result*?

#### CocoaPods
You can use [CocoaPods](http://cocoapods.org/) to install `YourLibrary` by adding it to your `Podfile`:

```ruby
platform :ios, '8.0'
use_frameworks!
pod 'YourLibrary'
```

To get the full benefits import `YourLibrary` wherever you import UIKit

``` swift
import UIKit
import YourLibrary
```
#### Carthage
Create a `Cartfile` that lists the framework and run `carthage bootstrap`. Follow the [instructions](https://github.com/Carthage/Carthage#if-youre-building-for-ios) to add `$(SRCROOT)/Carthage/Build/iOS/YourLibrary.framework` to an iOS project.

```
github "yourUsername/yourlibrary"
```
#### Manually
1. Download and drop ```YourLibrary.swift``` in your project.  
2. Congratulations!

**Comment by mdiep** [comment]
Result already has [a section in its README](https://github.com/antitypical/Result#integration) with some of this information. PRs that improve the documentation there would be welcome. ☺️ 

(But I'm vehemently against instructions to manually include source files in your project.)
