### ISSUE TITLE
Swift 3.0 branch

### ISSUE THREAD

**Issue by sunshinejr** [antitypical/Result#171]
Hey everyone! 🐼 

I was wondering if there is a chance for Swift 3.0 branch? Normally using Result with Swift 3.0 is alrighty, but I need to switch the "Use Legacy Swift Language Version" bool in Build Settings for Result every time.

Thanks!

**Comment by mdiep** [comment]
The `master` branch is targeting Swift 3. 😄

**Comment by sunshinejr** [comment]
Well, as I've said it uses `Use Legacy Swift Language Version`, which is desired effect for Swift 2.3, not Swift 3.0.

**Comment by mdiep** [comment]
`master` [doesn't](https://github.com/antitypical/Result/blob/2fe88d1d41615ed060489e8cd06fc1b3e8f0ca53/Result.xcodeproj/project.pbxproj#L627).

**Comment by sunshinejr** [comment]
Hmm, strange. Well, it must be problem on my end then, thanks.
