### ISSUE TITLE
Tag a release?

### ISSUE THREAD

**Issue by neilpa** [antitypical/Result#18]

**Comment by robrix** [comment]
I’m currently thinking it’d be good to wait til Swift 1.2 is final, but I’d appreciate others’ thoughts.

**Comment by jspahrsummers** [comment]
Since the final version of Swift 1.2 is unlikely to involve more language shifts, I think it'd be fine to tag now.

**Comment by robrix** [comment]
Fair enough.

**Comment by felixjendrusch** [comment]
*bump*

**Comment by robrix** [comment]
On it.

**Comment by robrix** [comment]
https://github.com/antitypical/Result/releases/tag/0.1

**Comment by neilpa** [comment]
:tada:
