### ISSUE TITLE
dematerialize() not working on linux

### ISSUE THREAD

**Issue by necrowman** [antitypical/Result#185]
For the moment I try build our library Boilerplate for last swift 3 on linux but it depends on your Result library.
I run ```swift build``` and take such error:
> Compile Swift Module 'Boilerplate' (16 sources)
>/home/travis/build/crossroadlabs/Boilerplate/Sources/Boilerplate/Error.swift:151:16: error: value of >type 'Result<Value, Error>' has no member 'dematerialize'
>    return try result.dematerialize()
>               ^~~~~~ ~~~~~~~~~~~~~
>/home/travis/build/crossroadlabs/Boilerplate/Sources/Boilerplate/Container.swift:58:20: error: value >of type 'Result<Self.Value, Self.Error>' has no member 'dematerialize'
>        return try withdrawResult().dematerialize()
>                   ^~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~
><unknown>:0: error: build had 1 command failures
>error: exit(1): /home/travis/build/crossroadlabs/swift-3.0-PREVIEW-6-ubuntu14.04/usr/bin/swift->build-tool -f /home/travis/build/crossroadlabs/Boilerplate/.build/debug.yaml

What happens and when it can be fixed for linux?

**Comment by ikesyo** [comment]
The method broke the build on DEVELOPMENT-SNAPSHOT-2016-08-15-a and was 	temporarily disabled: #183.

**Comment by ikesyo** [comment]
See also https://github.com/antitypical/Result/pull/182#discussion_r75149199.
