### ISSUE TITLE
Free functions for success and failure

### ISSUE THREAD

**Issue by neilpa** [antitypical/Result#19]
These were convenient in LlamaKit and wondering how you would feel about adding them here.

**Comment by robrix** [comment]
The `static` [`Result.success` and `Result.failure` functions](https://github.com/antitypical/Result/blob/master/Result/Result.swift#L19-L26) should be usable anywhere `success`/`failure` were, while also allowing you to explicitly specify the type (without resorting to `as` or a temporary variable) should the need arise.

**Comment by robrix** [comment]
Going to close this out for now, but feel free to reopen if there’s cases that the `static` functions don’t handle.

**Comment by neilpa** [comment]
The static functions are fine, mostly I was looking to save a few characters. Plus I hadn't even considered this which is nice

> while also allowing you to explicitly specify the type (without resorting to as or a temporary variable) should the need arise

**Comment by robrix** [comment]
Note that you can also write `.success(…)`/`.failure(…)` anywhere that Swift can infer the return type:

```swift
func yep() -> Result<String, String> {
    return .success("👍")
}
let nope: Result<String, String> = .failure("👎")
```

**Comment by neilpa** [comment]
Whoa, I thought that syntax was just for enum cases. It makes sense when I think about it though. They're both static properties/methods that need to be bound to a type.

**Comment by robrix** [comment]
Yep. Caveat lector: there are some corner cases where they can make compilation slow down unreasonably. I use the notation quite heavily myself, tho.
