### ISSUE TITLE
Errors from Apple APIs in Swift 3

### ISSUE THREAD

**Issue by AndrewSB** [antitypical/Result#190]
Currently, it isn't possible to construct a  `Result<Any, Error>`, or if you're using Swift 2.x, `Result<Any, ErrorType>`.

The rationale behind not using the `Error` or `ErrorType` protocol as a concrete type makes sense to me, **but** I've noticed an issue with the new APIs in Swift 3 that makes that constraint uncomfortable. 

For example in Core Bluetooth, Apple vends a number of functions that pass a `Error?`: 
```
open func peripheral(_ peripheral: CBPeripheral, didDiscoverServices error: Error?)
```
which was previously passing in an `NSError?`
```
func peripheral(peripheral: CBPeripheral, didDiscoverServices error: NSError?)
````

I had implemented a delegate for `CBPeripheralDelegate` that had wrapped the services or error returned from CoreBluetooth more concretely using a `Result`, instead of an optional array of services & an optional error:
```
open func peripheral(_ peripheral: CBPeripheral, didDiscoverServices error: Error?) {
   let result: Result<[CBService], Error>
    switch error {
    case .some(let err):
       result = .failure(err)
     case .none:
          guard let services = peripheral.services, !services.isEmpty else { 
                 assertionFailure("inconsistency, empty services w/o error"); return
          }
          result = .success(services)
    }
    consumers.forEach { $0.discoveredServices(result, fromPeripheral: peripheral) }
}
```

This code no longer works in Swift 3, since Apple now passes an `Error?` instead of an `NSError?`, and constructing a Result with an error type of `Error` isn't allowed.

So I'm not sure what should be done for this case. I could wrap Apple's `Error` in a struct, but that feels as if Im working against the framework. Is there some alternate way of composing a result without wrapping the error?

**Comment by NachoSoto** [comment]
You can explicitly bridge any `Error` to `NSError`:
```swift
let error: Error
let nsError: NSError = error as NSError
```

And if it's optional:

```swift
let error: Error?
let nsError: NSError? = error.map { $0 as NSError }
```

**Comment by AndrewSB** [comment]
@NachoSoto ahh, that makes a lot of sense.
Thank you!

Do you think one should not be able to construct a Result<Type, NSError> in that case? If it's possible to bridge any `Error` to an `NSError`?

**Comment by NachoSoto** [comment]
> Do you think one should not be able to construct a Result in that case?

If a type can't be instantiated, then you can't have a `Result` of that type :)

**Comment by AndrewSB** [comment]
@NachoSoto I edited my question, not sure why markdown parsed out the generic I had there

> Do you think one should not be able to construct a Result<Type, NSError> in that case

Your answer applies to either question though 😄
