### ISSUE TITLE
Avoid using custom operators in Swift 3

### ISSUE THREAD

**Issue by inamiy** [antitypical/Result#191]
It seems `>>-` operator no longer works seamlessly with other operator-centric libraries e.g. [Runes](https://github.com/thoughtbot/Runes), [Operadics](https://github.com/typelift/Operadics), due to the new `precedencegroup` in Swift 3. 

Formerly in Swift 2, `"error: ambiguous operator declarations found for operator"` did not occur iff `associativity` and `precedence` were totally equal, but this workaround no longer works in Swift 3, so I would like to suggest to either:
1. Remove custom operators in `Result`, or
2. Add de facto infix-operator library as a dependency (if there's any)

**Comment by mdiep** [comment]
I think we should adopt Runes.

**Comment by NachoSoto** [comment]
I'd vote for keeping Result dependency-free.

**Comment by mdiep** [comment]
> I'd vote for keeping Result dependency-free.

How would you vote to resolve the conflict? Remove the custom operators?

**Comment by NachoSoto** [comment]
That or renaming the operator, I suppose :/

**Comment by inamiy** [comment]
I also think dependency-free is the better choice.

- Remove `>>-` (use `flatMap` instead)
- Rename `&&&` to something else (e.g. `func fanout`)

**Comment by mdiep** [comment]
Given that we/I released a Result 3.0, how should we proceed? Remove them now and release a 4.0? Or deprecate them and release them whenever we're ready for 4.0?

**Comment by ikesyo** [comment]
If we re-define the operator at call site, we could use the both implementations at the same time. But that should be really confusing and doesn't look a right way.

```swift
import Foundation
import Result
import Runes

infix operator >>- : ChainingPrecedence

let result = Result<Int, NoError>.success(0)
result >>- { .success(String($0)) }

let optional: Int? = 1
optional >>- { $0 + 1 }
```

**Comment by inamiy** [comment]
Thanks, @ikesyo!
Overwriting at call site looks like a nice workaround.
I think just adding deprecation with message is sufficient for ver 3.x, and then remove custom operators in the future ver 4.0 (Swift 4).

**Comment by matrosovDev** [comment]
will you plan to update your library to support Swift 3? or what can you suggest to do? thank you

**Comment by ikesyo** [comment]
@matrosovDev Result already supports Swift 3 in [3.0.0](https://github.com/antitypical/Result/releases/tag/3.0.0) release.
