### ISSUE TITLE
Xcode 8.1 with Swift 3.0.1

### ISSUE THREAD

**Issue by bensarz** [antitypical/Result#194]
A release using Xcode 8.1 and Swift 3.0.1 is required to use the .zip file with Carthage.

**Comment by psparago** [comment]
Is there a workaround while waiting for the .zip that is compatible with Xcode 8.1 and Swift 3.0.1? I do not use Result directly and I'm not sure which of my dependencies does. Is there a way to get the source to compile through the Carthage build process as though Carthage did a Checkout or  does it have to be added to my source or ... ?

**Comment by bensarz** [comment]
@psparago you can use the hash of the commit you want to use in your Cartfile:

`github "antitypical/Result" "hash here"`

This will build the framework instead of using an prebuilt version. Building is quite fast and shouldn't impact your build times too much.

**Comment by ikesyo** [comment]
You can use `--no-use-binaries` option, don't need to modify your Cartfile.

**Comment by psparago** [comment]
Thank you @bensarz  and @ikesyo. I appreciate the speedy help.

**Comment by AndrewSB** [comment]
Can we reopen this to track uploading a binary compiled with Swift 3.0.1?
