### ISSUE TITLE
Report "SUCCESS" when network resources do not have a result

### ISSUE THREAD

**Issue by Blackjacx** [antitypical/Result#202]
Hey,

it's not an issue but rather a question:

How would you report Result.Success(...) when you actually do not have a result object. This situation can happen if you just cancel a process or delete something. Any ideas? Is there a way and I didn't saw it?

Thanks in advance.

**Comment by mdiep** [comment]
You can use a `Result<(), Error>` if you want to report success but don't have an actual value to pass.

**Comment by Blackjacx** [comment]
Thanks 👍
