### ISSUE TITLE
AnyError does not pass through localizedDescription from an underlying NSError

### ISSUE THREAD

**Issue by ratkins** [antitypical/Result#203]
My intuition is that the below test should pass, but it does not in release 3.1.0:

```
class AnyErrorSpec: QuickSpec {
    override func spec() {
        describe("AnyError") {
            it("forwards an underlying NSError's localizedDescription") {
                let error = NSError(domain: "Foo", code: 42, userInfo: [NSLocalizedDescriptionKey: "a localized description"])

                expect(AnyError(error).localizedDescription).to(equal("a localized description"))
            }
        }
    }
}

```

Should it? Would you accept a PR to make it so?

**Comment by ikesyo** [comment]
I expect you get the underlying error: `AnyError(error).error`. `localizedDescription` is not a requirement of `Error` protocol so `AnyError` does not implement it.

**Comment by ratkins** [comment]
If `localizedDescription` isn't a property of `Error` (and you're right, it's not), why does this even parse?

```
let foo: AnyError = AnyError(error)
let bar: String = foo.localizedDescription

```

**Comment by ikesyo** [comment]
See https://github.com/apple/swift-evolution/blob/master/proposals/0112-nserror-bridging.md

> In Foundation, add an extension to `ErrorProtocol` that provides access to the localized description, which is available for all error types.

**Comment by ratkins** [comment]
Aha, I see, so implementing this for Result's `AnyError` would introduce a dependency on Foundation which you probably don't want to do. We can just add this locally then.

**Comment by ikesyo** [comment]
It might make sense to conform to `LocalizedError` protocol and delegate to the underlying error.
