### ISSUE TITLE
Combination function instead of &&&

### ISSUE THREAD

**Issue by DivineDominion** [antitypical/Result#211]
I am using RxSwift in my current project and like how `Observable.combineLatest` reads, for example. Combining two `Result`s works well with the &&& operator, but the resulting code isn't quite what I expected. So I figured a static function like `Result.combine` would work well.

    public static func combine<L : ResultProtocol, R : ResultProtocol>
        (_ left: L, _ right: R, resultSelector: (L.Value, R.Value) -> T)
        -> Result<T, L.Error> where L.Error == R.Error {

            return left.flatMap { outer in
                right.map { inner in
                    resultSelector(outer, inner)
                }
            }
    }

Problem is: `T` cannot be inferred on the call side this way. I wonder if (1) this is something you'd be interested in merging anyway before I investigate, and (2) if you may have a clue why that causes trouble. Is it because Result is an enum? 🤔

**Comment by ikesyo** [comment]
> but the resulting code isn't quite what I expected

What you wrote should be the same as `(left &&& right).map(resultSelector)`. Why do yo need the alternative implementation?

**Comment by ikesyo** [comment]
> if you may have a clue why that causes trouble. Is it because Result is an enum?

The `T` type variable is missing from the generic parameter list.

**Comment by DivineDominion** [comment]
Ah yes, forgot to menthion that -- leaving it out or putting it in doesn't change a thing in regard do the "could not infer generic type T" message, though. (I have a pet theory why the compiler doesn't need it for static functions, but I don't have a real clue.)
