### ISSUE TITLE
Build failed on Linux with swift 3.1

### ISSUE THREAD

**Issue by KelvinJin** [antitypical/Result#212]
Sorry to bother you guys with the pre-released swift version. I just want you to know this issue.

The issue was reported [here](https://bugs.swift.org/browse/SR-3872). And the apple guys confirmed the issue is intended behaviour. The related code is [here](https://github.com/antitypical/Result/blob/master/Result/Result.swift#L128-L135).

This actually won't be an issue once we remove these deprecated methods.

**Comment by norio-nomura** [comment]
I know the issue and fix is here. https://github.com/antitypical/Result/commit/011a8c9e56e5efd8ca01dc6049e9d8eb6ddc5c93
Could you please try `swift package edit Result --revision nn-swift-3.1-on-linux`  in your project directory before running `swift build` for confirming fixed by that?

**Comment by KelvinJin** [comment]
@norio-nomura Oh, didn't know you fix it! That's cool. So I guess instead of fatal error, should we just remove these two methods?

**Comment by norio-nomura** [comment]
I can not believe that all users have already completed the transition.

**Comment by KelvinJin** [comment]
@norio-nomura oh, no. I'm not saying we release it now. Sure we'll wait for Swift 3.1 official release. But when it comes out, instead of just crash the app, we should probably force them to update? It's entirely up to you guys. I'm a happy user as long as this can be built :))))

**Comment by norio-nomura** [comment]
Ah, we should change them from `deprecated` to `unavailable`.

**Comment by ikesyo** [comment]
This should have been fixed in 3.2.1 release. Please check it out! 🙏
