### ISSUE TITLE
Carthage with option --cache-builds not working

### ISSUE THREAD

**Issue by Dschee** [antitypical/Result#218]
Hi, I'm using a quite big Cartfile in an iOS app. Now when I run the command 
```
carthage update --platform ios --cache-builds --no-use-binaries
```
twice every single framework says "Valid cache found for Framework, skipping build" except for this Library, where I get

> **Invalid** cache found for Result, rebuilding with all downstream dependencies

Do you know **why** this might be the case? This is causing my rebuilds to take very long unnecessarily ...

The way I include Result in my **Cartfile** is indirect (via Moya):

``` Swift
github "Moya/Moya" ~> 8.0
```

**Comment by mdiep** [comment]
This is probably https://github.com/Carthage/Carthage/issues/1800.
