### ISSUE TITLE
Lower the `Error: Swift.Error` constraint on `Result` temporarily.

### ISSUE THREAD

**Issue by andersio** [antitypical/Result#231]
We currently provide an `AnyError` that can be used when multiple error types are to blend together in an opaque way to the type system. While it is a workaround, it isn't particularly great in usability.

It makes me wonder if we can lower the `Error: Swift.Error` constraint on `Result` temporarily, so that we may construct `Result<U, Error>` with Error being the existential. The constraint would now be in places that decides the error type, e.g.

```swift
extension Result {
	/// Constructs a failure wrapping an `error`.
	public init(error: Error) where Error: Swift.Error {
		self = .failure(error)
	}
}

extension Result where Error == Swift.Error {
	/// Constructs a failure wrapping an `error`.
	public init(error: Swift.Error) {
		self = .failure(error)
	}
}
```

We can still have the static guarantee that `Error` is an error, and it would not break any API use even if we eventually lift the constraint back to the types as the `Error` existential gains `Error` conformance.

@mdiep @ikesyo

**Comment by mdiep** [comment]
Wouldn't this mean that `Result.error` wouldn't conform to `Swift.Error`?

This conformance seems like an important part of the contract.

**Comment by andersio** [comment]
> Wouldn't this mean that Result.error wouldn't conform to Swift.Error?

Yes, but we would prohibit the construction of `Result` with `Error` types other than those conforming to `Swift.Error`. So one can write `Result<Int, Int>`, but no initialisers or operators would be available for use.

**Comment by mdiep** [comment]
What's the benefit of lowering the constraint? Can you share an example where you'd see a benefit?

**Comment by andersio** [comment]
It just helps whenever I need to deal with composing signals or producers with multiple kinds of errors in ReactiveSwift. That said after a second thought I guess it is probably better to add overloads for the `Error` existential and allow `AnyError` to be inferred in some cases.
