### ISSUE TITLE
Why not declare 'Result' as 'Result<T>'? So it easy to deal with different types of errors.

### ISSUE THREAD

**Issue by raymondCaptain** [antitypical/Result#247]
When I use RxSwift and Result, I get the error 

`Using 'Error' as a concrete type conforming to protocol 'Error' is not supported`

I realized I need provide a concrete Error subtype.
I got a solution by use 'AnyError', but why not declare 'Result' as this？

`enum Result<Value> {
    case value(Value)
    case error(Error)
}` 

Then we can 

`return Result<Int>.error(APIError.returnFalseFromServer)`

and

`return Result<Int>.error(UserOperationError.inputError)`

I've read the discuss in closed issues, can i get more information？

**Comment by mdiep** [comment]
Because we believe there's value in typed errors. This lets you:

1. See what errors will occur, with autocompletion
2. Exhaustively handle errors if you choose

**Comment by raymondCaptain** [comment]
I got it. It's a good idea. Thx

**Comment by raymondCaptain** [comment]
If we use typed error, how should I deal with this situation?
There's three step in logic A, step1, step2, step3, which occur error1, error2, error3.
Then I declare enum as this
`enum AnError: Error {
    case error1,
    case error2, 
    case error3
}`
Now, in another logic, logic B, I need reuse step2 in logic A, which occur error2.
'Result' request the error is the same type, so all the error can be deliver to the end of the logic for centralized treatment.
Should I add more error to AnError? But the error in Logic B will not happen in Logic A.

**Comment by raymondCaptain** [comment]
Can I get some help?

**Comment by mdiep** [comment]
I would do something like this:

```
struct Error2: Error { … }

enum AnError: Error {
    case error1
    case error2(Error2)
    case error3
}

func a() -> Result<X, AnError> {
    // This could call b and wrap it in AnError.error2
}

func b() -> Result<X, Error2> {
}
```

**Comment by raymondCaptain** [comment]
Thanks for your help
