### ISSUE TITLE
Proposal: remove Prelude dependency

### ISSUE THREAD

**Issue by jspahrsummers** [antitypical/Result#27]
Although I like what [Prelude](https://github.com/robrix/Prelude) is trying to accomplish, it seems out-of-place as a dependency for Result. Every added dependency is an additional burden for consumers, and Prelude specifically doesn't seem to add enough value _here_ to justify it being a requirement.

c.f. [the conversation from #reactivecocoa](https://reactivex.slack.com/archives/reactivecocoa/p1429157460000503)

/cc @nachosoto @saniul @tony

**Comment by jspahrsummers** [comment]
Related to #28.

**Comment by jspahrsummers** [comment]
Also, correct me if I'm wrong, but we want **this framework** to be the standardized `Result` type across every Swift project (you know, dream big or go home).

If that's the case, we need to win the hearts and minds of the Swift programmers who are turned off by long dependency lists, and who just want to solve the problem immediately in front of themselves. Making the framework appear smaller will garner broader appeal.

**Comment by robrix** [comment]
`Prelude`’s required by `Either`. That can be changed, of course.

**Comment by rnapier** [comment]
I agree that Result should be as stand-alone as possible. I get the Box dependency, but Prelude is too big a lift IMO, particularly for how little it is needed by this code.

Related discussion: http://stackoverflow.com/a/29540037/97337 (see the comments)

I'd much rather a few lines of code duplication than a 4-framework bundle.

As an alternative, I've been thinking about how to automate combining all the dependencies into a one-file bundle.

**Comment by robrix** [comment]
@rnapier: I don’t follow how the comments at that link relate to this?

> I'd much rather a few lines of code duplication than a 4-framework bundle.

There are two things at play here:

1. are the reasons to eschew dependencies _well-founded_, and
2. will people come around?

I’ve yet to hear a well-founded argument against µframework dependencies (modulo issues with `xcodebuild`, grumble grumble), but the second one is more interesting. We familiarize users with smaller factoring by use of Result.framework; is that enough?

I think it will be, in time. I don’t know, though. Maybe not.

**Comment by jspahrsummers** [comment]
> `Prelude`’s required by `Either`.

Ah, my bad—I thought `Result` brought it in independently for some reason.

We can focus this discussion on #28, then.
