### ISSUE TITLE
Proposal: remove Either dependency

### ISSUE THREAD

**Issue by jspahrsummers** [antitypical/Result#28]
It's indisputable that `Result` is a kind of `Either`, but every added dependency is an additional burden for consumers, who I'm not convinced will use the `EitherType` functionality directly.

Furthermore, the Either [README](https://github.com/robrix/Either/blob/8d3f69d109436f74f68e4828a75be87eea12fa4b/README.md#use) even suggests that its functionality can be trivially added as an extension upon a pre-existing `Result` type. To me, this means that consumers should not be _required_ to build and link Either just to use a standardized `Result` type.

c.f. [the conversation from #reactivecocoa](https://reactivex.slack.com/archives/reactivecocoa/p1429157460000503)

/cc @nachosoto @saniul @tony

**Comment by jspahrsummers** [comment]
From #27:

> Also, correct me if I'm wrong, but we want **this framework** to be the standardized `Result` type across every Swift project (you know, dream big or go home).
>
> If that's the case, we need to win the hearts and minds of the Swift programmers who are turned off by long dependency lists, and who just want to solve the problem immediately in front of themselves. Making the framework appear smaller will garner broader appeal.

**Comment by robrix** [comment]
Definitely doable. I don’t much like the idea, but it’s doable.

I think we can also win the hearts/minds of Swift programmers turned off by long dependency lists by simply continuing to exist. “Long dependency lists” is a non-issue with µframeworks and I think programmers will come around.

Overall I’m not sure this is a problem that we need to solve.

**Comment by rnapier** [comment]
I think long dependency lists continue to be a turnoff, even with µframeworks. It forces something like Carthage at a minimum, and even with Carthage, requires several steps to get all of them in place (it even starts to encourage CocoaPods-like solutions, which I think should be overkill).

My preferred solution for ObjC dependency management has been to just check the files into my own repository (with a README detailing the URL and SHA I pulled from), and then just add the source files to my project directly. I haven't tried to ship a Swift thing yet, but I'm not really keen on shipping dynamic (but unshared) libraries if I can avoid it. I'd rather get whole-program optimization across my deps.

I'm not saying it's make-or-break, and of course the Swift world will be different than ObjC, but it definitely turns me off from Result (and I've proven I'm a huge fan).

I believe that frameworks should have minimal sub-dependencies (even if it requires small amounts of code duplication or less beautiful framework code) and easily click together without being a major commitment to the program.

**Comment by neilpa** [comment]
Having integrated `Result` into several toy projects I'm torn on this issue. I appreciate the minimalism of these frameworks but each time I wonder if four frameworks are really needed. I also find myself groaning at the tediousness of having to update both the target and tests with the right linkage and copying.

On the other hand, once you've got built frameworks there's zero difference between adding two frameworks (`Result` + `Box`) vs four. It's just a matter of multi-selecting the right ones when batch importing into Xcode.

Overall though I find the case for `Either` as dependency the weakest of the bunch. It's an opportunistic one that'll be rarely used by consumers just looking for a blessed `Result` type.

**Comment by neilpa** [comment]
There's also an opportunity for supplementary tooling that eases the perceived pain of adding a framework dependency. I point the tool at some frameworks and it does the [manual steps outlined here](https://github.com/Carthage/Carthage#adding-frameworks-to-an-application).

**Comment by jspahrsummers** [comment]
> I think we can also win the hearts/minds of Swift programmers turned off by long dependency lists by simply continuing to exist. “Long dependency lists” is a non-issue with µframeworks and I think programmers will come around.

This definitely applies to _most_ projects, but I think it utterly fails for anything that's intended to be “the standard.”

We want antitypical/Result to be _the_ `Result` type that everyone uses, right? If that's the case, we can't afford to be super prescriptive about the right or best way to do things, because that turns people away. We'll have much more success by being accepting of typical development practices, and receptive to what most folks want.

And while I think it's a little silly that this is the case, I think it's fair to say that a significant number of folks don't want to use 4 frameworks just to obtain a `Result` type.

**Comment by robrix** [comment]
Okay.
