### ISSUE TITLE
Example os import usage for Swift 5/4

### ISSUE THREAD

**Issue by jimisaacs** [antitypical/Result#283]
I might be doing something wrong, or missed some docs, but after upgrading to 10.2, the `Result` enum can't be found. I think I'm doing something wrong, and would like to just ask for some direction, and maybe a doc callout for proper import usage.

**Comment by NachoSoto** [comment]
If you’re building with 10.2, there’s little point to using this dependency anymore :)

**Comment by mdiep** [comment]
It should work just as before. Can you share what you're doing and what error you're seeing?

**Comment by jimisaacs** [comment]
<img width="653" alt="Screen Shot 2019-03-26 at 1 00 00 PM" src="https://user-images.githubusercontent.com/299156/55029335-14f1fc00-4fc7-11e9-96db-e45661d54eab.png">

**Comment by jimisaacs** [comment]
@NachoSoto can you clarify? If I'm still supporting iOS 11, or still have dependencies that build for Swift 4.2? Do I need this dependency? Sorry if I'm not completely up to speed on all things upgrade, just giving it a shot to see what breaks.

**Comment by NachoSoto** [comment]
Result is part of the Swift standard library that you’re including with your binary. As long as you’re compiling with a newer version of the compiler, you have access to Result, regardless of iOS / dependencies Swift versions.

**Comment by jimisaacs** [comment]
@NachoSoto Ok, so I think the issue there is a namespace one, and particularly with Apollo. Let me share the full imports.
<img width="695" alt="Screen Shot 2019-03-26 at 1 14 54 PM" src="https://user-images.githubusercontent.com/299156/55030318-60a5a500-4fc9-11e9-99f6-75ab7f8c778c.png">

Apollo defines it's own `Result`, and I had a conflict that was more easily resolved by doing the targeted import on `Result` (less to import).

Now for me to remove `Result`. I'd have to do to things (among many other options).
1. Remove Result
2. Change all references to `Swift.Result`.

Of course other options are, make a PR against Apollo, but we have other issues there that complicate that route.

Does this outline sound like the right approach? Or from what I've shared, should importing `Result` the way I am still work?

**Comment by mdiep** [comment]
Oh, in Swift 5 mode, this repo doesn't define `Result` as an enum—it just extends the type from the Standard library. You can probably remove that import entirely or change it to `import Result` and it should work.

`import enum Result.Result` will no longer work because, as it says, the Result module no longer defines that enum.

**Comment by jimisaacs** [comment]
Hmm, ok, it looks like I can't get around doing the targeted import on Apollo then. thanks for the help!

**Comment by jimisaacs** [comment]
Just following up, targeted import on Apollo and removal of import of Result works.
