### ISSUE TITLE
Cocoapods instructions still pin to v4

### ISSUE THREAD

**Issue by robinkunde** [antitypical/Result#288]
First of all, great work on this update!

The issue:
v5 was just released but it doesn't look like the README has been updated and still tells users to pin to v4. 

```pod 'Result', '~> 4.0.0'```

**Comment by tapsandswipes** [comment]
Also, not setting a pod version in pod file do not get v5. It installs `4.0.1`

**Comment by mdiep** [comment]
Someone may need to push the pod. @ikesyo?

**Comment by ikesyo** [comment]
- Result 5.0 has been pushed to CocoaPods trunk
- Submitted #289 to update README
