### ISSUE TITLE
Tests depend on Prelude

### ISSUE THREAD

**Issue by tjw** [antitypical/Result#32]
It looks like 1756b77893c693871642a5302ab51f2a63e297f7 intended to remove the dependency on Prelude, but the tests still import it and use `unit()` in `ResultTests.testInitOptionalSuccess()`

**Comment by robrix** [comment]
Oof, good catch. Guess I still had Prelude.framework in my `BUILT_PRODUCTS_DIR` when I ran the tests :sob:
