### ISSUE TITLE
Restore Box.framework as a dependency

### ISSUE THREAD

**Issue by robrix** [antitypical/Result#36]
`Result` as a `struct` is [awkward to use](https://github.com/ReactiveCocoa/ReactiveCocoa/pull/1933#discussion_r28931968) and having a public `Box` that isn’t a separate dependency will only lead to ambiguities.

So per discussion in that PR, we’ll restore `Box` to Box.framework and `Result` will be an `enum` once more.

**Comment by robrix** [comment]
Think I’ll call the attendant release “Hi, Haters.”

**Comment by iCodesign** [comment]
:clap:
