### ISSUE TITLE
CocoaPods release?

### ISSUE THREAD

**Issue by giacgbj** [antitypical/Result#38]
Will there ever be?

**Comment by robrix** [comment]
[There already is](https://cocoapods.org/pods/Result) :blush:

**Comment by giacgbj** [comment]
Thanks, I'd suggest to update the https://github.com/antitypical/Result#integration section ;)

**Comment by robrix** [comment]
My understanding is that anybody can update the pod at any time, so I’d recommend you do that.

You won’t have to change _everything_ going from 0.3.2 to 0.4; in fact you shouldn’t have to change anything, you’ll just be able to use pattern matching & a public `Box` type.
