### ISSUE TITLE
Carthage update fails

### ISSUE THREAD

**Issue by giacgbj** [antitypical/Result#39]
I tried to install Result using the following Cartfile:

github "antitypical/Result" ~> 0.2

The result is the following output:

<pre>
$ carthage update
*** Fetching Result
*** Fetching Either
*** Fetching Box
*** Fetching Prelude
*** Checking out Box at "18d05a56845837eea90a36854c67de2520983bf8"
*** Checking out Result at "0.2"
*** Checking out Prelude at "180e9ae5e60ec47abd8f3e0fa68cafbbbd160abe"
*** Checking out Either at "026d3471bca7c9573fdec46bab3d8f265d2ec001"
*** xcodebuild output can be found in /var/folders/p2/v0630kzj4lb8v65d325zn5vh0000gn/T/carthage-xcodebuild.SE01YO.log
*** Building scheme "Box-iOS" in Box.xcodeproj
objc[36929]: Class XCBuildConfiguration is implemented in both /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/Frameworks/DevToolsCore.framework/Versions/A/DevToolsCore and /Users/jhack/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Peckham.xcplugin/Contents/Frameworks/MHImportBuster.framework/Versions/A/MHImportBuster. One of the two will be used. Which one is undefined.
2015-04-27 16:09:22.961 xcodebuild[36929:1141196] [MT] iPhoneSimulator: SimVerifier returned: Error Domain=NSPOSIXErrorDomain Code=53 "Simulator verification failed." UserInfo=0x7f87ba392f20 {NSLocalizedFailureReason=A connection to the simulator verification service could not be established., NSLocalizedRecoverySuggestion=Ensure that Xcode.app is installed on a volume with ownership enabled., NSLocalizedDescription=Simulator verification failed.}
** BUILD FAILED **

The following build commands failed:
	CompileC /Users/jhack/Library/Developer/Xcode/DerivedData/Box-dhuserewjevjzmhhrmurzekzdvvl/Build/Intermediates/Box.build/Release-iphoneos/Box-iOS.build/Objects-normal/armv7/Box_vers.o /Users/jhack/Library/Developer/Xcode/DerivedData/Box-dhuserewjevjzmhhrmurzekzdvvl/Build/Intermediates/Box.build/Release-iphoneos/Box-iOS.build/DerivedSources/Box_vers.c normal armv7 c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/jhack/Library/Developer/Xcode/DerivedData/Box-dhuserewjevjzmhhrmurzekzdvvl/Build/Intermediates/Box.build/Release-iphoneos/Box-iOS.build/Objects-normal/arm64/Box_vers.o /Users/jhack/Library/Developer/Xcode/DerivedData/Box-dhuserewjevjzmhhrmurzekzdvvl/Build/Intermediates/Box.build/Release-iphoneos/Box-iOS.build/DerivedSources/Box_vers.c normal arm64 c com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)
</pre>

where "/var/folders/p2/v0630kzj4lb8v65d325zn5vh0000gn/T/carthage-xcodebuild.SE01YO.log" contains

<pre>
Build settings from command line:
    SDKROOT = iphonesimulator8.3

=== BUILD TARGET Box-iOS OF PROJECT Box WITH CONFIGURATION Release ===

Check dependencies

CompileC /Users/jhack/Library/Developer/Xcode/DerivedData/Box-dhuserewjevjzmhhrmurzekzdvvl/Build/Intermediates/Box.build/Release-iphoneos/Box-iOS.build/Objects-normal/armv7/Box_vers.o /Users/jhack/Library/Developer/Xcode/DerivedData/Box-dhuserewjevjzmhhrmurzekzdvvl/Build/Intermediates/Box.build/Release-iphoneos/Box-iOS.build/DerivedSources/Box_vers.c normal armv7 c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/jhack/workspace/uPen/Carthage/Checkouts/Box
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:(null)/Users/jhack/.gem/ruby/2.0.0(null):(null)/Library/Ruby/Gems/2.0.0(null):(null)/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0(null):/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/Cellar/sonar-runner/2.4/libexec/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -fmodules -fmodules-cache-path=/Users/jhack/Library/Developer/Xcode/DerivedData/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/jhack/Library/Developer/Xcode/DerivedData/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Xclang -fmodule-implementation-of -Xclang Box -fapplication-extension -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wunreachable-code -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.3.sdk -fexceptions -fstrict-aliasing -Wdeprecated-declarations -g -Wno-sign-conversion -mios-simulator-version-min=8.0 -iquote /Users/jhack/Library/Developer/Xcode/DerivedData/Box-dhuserewjevjzmhhrmurzekzdvvl/Build/Intermediates/Box.build/Release-iphoneos/Box-iOS.build/Box-generated-files.hmap -I/Users/jhack/Library/Developer/Xcode/DerivedData/Box-dhuserewjevjzmhhrmurzekzdvvl/Build/Intermediates/Box.build/Release-iphoneos/Box-iOS.build/Box-own-target-headers.hmap -I/Users/jhack/Library/Developer/Xcode/DerivedData/Box-dhuserewjevjzmhhrmurzekzdvvl/Build/Intermediates/Box.build/Release-iphoneos/Box-iOS.build/Box-all-non-framework-target-headers.hmap -ivfsoverlay /Users/jhack/Library/Developer/Xcode/DerivedData/Box-dhuserewjevjzmhhrmurzekzdvvl/Build/Intermediates/Box.build/all-product-headers.yaml -iquote /Users/jhack/Library/Developer/Xcode/DerivedData/Box-dhuserewjevjzmhhrmurzekzdvvl/Build/Intermediates/Box.build/Release-iphoneos/Box-iOS.build/Box-project-headers.hmap -I/Users/jhack/Library/Developer/Xcode/DerivedData/Box-dhuserewjevjzmhhrmurzekzdvvl/Build/Products/Release-iphoneos/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Users/jhack/Library/Developer/Xcode/DerivedData/Box-dhuserewjevjzmhhrmurzekzdvvl/Build/Intermediates/Box.build/Release-iphoneos/Box-iOS.build/DerivedSources/armv7 -I/Users/jhack/Library/Developer/Xcode/DerivedData/Box-dhuserewjevjzmhhrmurzekzdvvl/Build/Intermediates/Box.build/Release-iphoneos/Box-iOS.build/DerivedSources -F/Users/jhack/Library/Developer/Xcode/DerivedData/Box-dhuserewjevjzmhhrmurzekzdvvl/Build/Products/Release-iphoneos -MMD -MT dependencies -MF /Users/jhack/Library/Developer/Xcode/DerivedData/Box-dhuserewjevjzmhhrmurzekzdvvl/Build/Intermediates/Box.build/Release-iphoneos/Box-iOS.build/Objects-normal/armv7/Box_vers.d --serialize-diagnostics /Users/jhack/Library/Developer/Xcode/DerivedData/Box-dhuserewjevjzmhhrmurzekzdvvl/Build/Intermediates/Box.build/Release-iphoneos/Box-iOS.build/Objects-normal/armv7/Box_vers.dia -c /Users/jhack/Library/Developer/Xcode/DerivedData/Box-dhuserewjevjzmhhrmurzekzdvvl/Build/Intermediates/Box.build/Release-iphoneos/Box-iOS.build/DerivedSources/Box_vers.c -o /Users/jhack/Library/Developer/Xcode/DerivedData/Box-dhuserewjevjzmhhrmurzekzdvvl/Build/Intermediates/Box.build/Release-iphoneos/Box-iOS.build/Objects-normal/armv7/Box_vers.o
clang: error: invalid architecture 'arm' for deployment target '-mios-simulator-version-min=8.0'

CompileC /Users/jhack/Library/Developer/Xcode/DerivedData/Box-dhuserewjevjzmhhrmurzekzdvvl/Build/Intermediates/Box.build/Release-iphoneos/Box-iOS.build/Objects-normal/arm64/Box_vers.o /Users/jhack/Library/Developer/Xcode/DerivedData/Box-dhuserewjevjzmhhrmurzekzdvvl/Build/Intermediates/Box.build/Release-iphoneos/Box-iOS.build/DerivedSources/Box_vers.c normal arm64 c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/jhack/workspace/uPen/Carthage/Checkouts/Box
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:(null)/Users/jhack/.gem/ruby/2.0.0(null):(null)/Library/Ruby/Gems/2.0.0(null):(null)/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0(null):/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/Cellar/sonar-runner/2.4/libexec/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c -arch arm64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -fmodules -fmodules-cache-path=/Users/jhack/Library/Developer/Xcode/DerivedData/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/jhack/Library/Developer/Xcode/DerivedData/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Xclang -fmodule-implementation-of -Xclang Box -fapplication-extension -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wunreachable-code -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.3.sdk -fexceptions -fstrict-aliasing -Wdeprecated-declarations -g -Wno-sign-conversion -mios-simulator-version-min=8.0 -iquote /Users/jhack/Library/Developer/Xcode/DerivedData/Box-dhuserewjevjzmhhrmurzekzdvvl/Build/Intermediates/Box.build/Release-iphoneos/Box-iOS.build/Box-generated-files.hmap -I/Users/jhack/Library/Developer/Xcode/DerivedData/Box-dhuserewjevjzmhhrmurzekzdvvl/Build/Intermediates/Box.build/Release-iphoneos/Box-iOS.build/Box-own-target-headers.hmap -I/Users/jhack/Library/Developer/Xcode/DerivedData/Box-dhuserewjevjzmhhrmurzekzdvvl/Build/Intermediates/Box.build/Release-iphoneos/Box-iOS.build/Box-all-non-framework-target-headers.hmap -ivfsoverlay /Users/jhack/Library/Developer/Xcode/DerivedData/Box-dhuserewjevjzmhhrmurzekzdvvl/Build/Intermediates/Box.build/all-product-headers.yaml -iquote /Users/jhack/Library/Developer/Xcode/DerivedData/Box-dhuserewjevjzmhhrmurzekzdvvl/Build/Intermediates/Box.build/Release-iphoneos/Box-iOS.build/Box-project-headers.hmap -I/Users/jhack/Library/Developer/Xcode/DerivedData/Box-dhuserewjevjzmhhrmurzekzdvvl/Build/Products/Release-iphoneos/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Users/jhack/Library/Developer/Xcode/DerivedData/Box-dhuserewjevjzmhhrmurzekzdvvl/Build/Intermediates/Box.build/Release-iphoneos/Box-iOS.build/DerivedSources/arm64 -I/Users/jhack/Library/Developer/Xcode/DerivedData/Box-dhuserewjevjzmhhrmurzekzdvvl/Build/Intermediates/Box.build/Release-iphoneos/Box-iOS.build/DerivedSources -F/Users/jhack/Library/Developer/Xcode/DerivedData/Box-dhuserewjevjzmhhrmurzekzdvvl/Build/Products/Release-iphoneos -MMD -MT dependencies -MF /Users/jhack/Library/Developer/Xcode/DerivedData/Box-dhuserewjevjzmhhrmurzekzdvvl/Build/Intermediates/Box.build/Release-iphoneos/Box-iOS.build/Objects-normal/arm64/Box_vers.d --serialize-diagnostics /Users/jhack/Library/Developer/Xcode/DerivedData/Box-dhuserewjevjzmhhrmurzekzdvvl/Build/Intermediates/Box.build/Release-iphoneos/Box-iOS.build/Objects-normal/arm64/Box_vers.dia -c /Users/jhack/Library/Developer/Xcode/DerivedData/Box-dhuserewjevjzmhhrmurzekzdvvl/Build/Intermediates/Box.build/Release-iphoneos/Box-iOS.build/DerivedSources/Box_vers.c -o /Users/jhack/Library/Developer/Xcode/DerivedData/Box-dhuserewjevjzmhhrmurzekzdvvl/Build/Intermediates/Box.build/Release-iphoneos/Box-iOS.build/Objects-normal/arm64/Box_vers.o
clang: error: invalid architecture 'aarch64' for deployment target '-mios-simulator-version-min=8.0'
</pre>

This happens on Mac OS X 10.10.3 (14D136), Xcode 6.3.1 (6D1002) (=> Swift 1.2).

**Comment by robrix** [comment]
Does this happen with `0.4`?

**Comment by giacgbj** [comment]
No, it doesn't, and I don't have any reason to stick to the 0.2 version, so you can consider this issue closed.

I thought that "~> 0.2" would have been resolved to the latest 0.* version :-)

**Comment by mdiep** [comment]
> I thought that "~> 0.2" would have been resolved to the latest 0.* version :-)

For versions < 1.0, the second number constitutes a major release. So 0.3 is a new major release that's incompatible with 0.2.
