### ISSUE TITLE
Carthage build fails

### ISSUE THREAD

**Issue by Odrakir** [antitypical/Result#52]
I'm trying to install ReactiveCocoa through Carthage with no success, I've come to the conclusion that the problem is in building Result framework, so I tried with this cartfile:

`github "antitypical/Result" == 0.4.2`

This is what I do:
```
MacBook-Pro-de-Ricardo-2:RACTest Ricardo$ carthage update
*** Fetching Result
*** Fetching Box
*** Downloading Box at "1.2.2"
*** Checking out Result at "0.4.2"
*** xcodebuild output can be found in /var/folders/7g/3ysplhns0mndfwr4h535nfr00000gn/T/carthage-xcodebuild.mordHg.log
*** Building scheme "Result-iOS" in Result.xcworkspace
A shell task failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/Ricardo/Library/Developer/Xcode/DerivedData/Result-hktjintpcyyecvfaasfnmpejpkph/Build/Intermediates/Box.build/Release-iphoneos/Box-iOS.build/Objects-normal/armv7/Box_vers.o /Users/Ricardo/Library/Developer/Xcode/DerivedData/Result-hktjintpcyyecvfaasfnmpejpkph/Build/Intermediates/Box.build/Release-iphoneos/Box-iOS.build/DerivedSources/Box_vers.c normal armv7 c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/Ricardo/Library/Developer/Xcode/DerivedData/Result-hktjintpcyyecvfaasfnmpejpkph/Build/Intermediates/Box.build/Release-iphoneos/Box-iOS.build/Objects-normal/arm64/Box_vers.o /Users/Ricardo/Library/Developer/Xcode/DerivedData/Result-hktjintpcyyecvfaasfnmpejpkph/Build/Intermediates/Box.build/Release-iphoneos/Box-iOS.build/DerivedSources/Box_vers.c normal arm64 c com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)
```

And this is the log: https://gist.github.com/Odrakir/9f36dd16d7872bdb9c15

I've been searching around and I did everything I found as a possible solution: Deleting carthage cache, deleting Simulators, reinstalling Xcode... nothing seems to work

**Comment by robrix** [comment]
I can’t reproduce this with carthage 0.7.3 and a Cartfile containing:

```
github "antitypical/Result" ~> 0.4.2
```

(You typically want `~>` instead of `==` to select compatible versions instead of pinning to specific versions.)

**Comment by robrix** [comment]
I should also note, I’m using the Xcode 6.4 betas currently. What version of Xcode are you using?

**Comment by Odrakir** [comment]
I'm on 6.3. I was about to download 6.2 and try with that, but I'll try with 6.4 beta instead.

**Comment by Odrakir** [comment]
Exact same output with 6.4. I guess there's something weird going on on my machine.

**Comment by robrix** [comment]
Sounds like :confused:

I don’t think there’s any action for me to take on this end, so I’m going to close this out. Sorry I wasn’t able to help!
