### ISSUE TITLE
Release 0.4.4

### ISSUE THREAD

**Issue by ikesyo** [antitypical/Result#59]
Would you mind releasing 0.4.4 at 81b1896 for Swift 1.2, with the changes included in [0.5](https://github.com/antitypical/Result/releases/tag/0.5) for Swift 2? :pray:

**Comment by gfontenot** [comment]
@robrix I can do this if you don't have any objections

**Comment by robrix** [comment]
:+1: (and thank you)

**Comment by gfontenot** [comment]
:boom: done

**Comment by ikesyo** [comment]
Many thanks! :sparkling_heart:
