### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by robrix** [antitypical/Result#6]

**Comment by sync** [comment]
Travis CI won't do Xcode 7, Ship.io has Xcode 7 support for example https://ship.io/xcode-7-beta-is-here/, their support is good, but a bit more limited to what Travis CI offer (for example require a workspace, can't install gem like xcpretty but xctool is installed) Work around is to use our own makefile etc...)

**Comment by robrix** [comment]
:+1:

**Comment by gfontenot** [comment]
Circle supports Xcode 7 now, as well. I've been really happy with it.
