### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by sync** [antitypical/Result#70]
quite a few changes were made since https://github.com/antitypical/Result/releases/tag/0.5 perhaps it's time to create a new releases...

**Comment by robrix** [comment]
Possibly a prerelease, but I’d like to avoid 0.6 final til Swift 2 lands.

**Comment by sync** [comment]
agreed a prerelease, up to you :-)

**Comment by Thomvis** [comment]
A release on CocoaPods with Swift 2 compatibility would also be much appreciated! :smile:

**Comment by robrix** [comment]
@Thomvis I’ve invited you to the repo. PRs are appreciated for any non-trivial changes, but you’d be welcome to tag e.g. 0.6-beta1 at your leisure :smile:

**Comment by Thomvis** [comment]
@robrix thanks so much!

I've created a 0.6-beta.1 release. Let me know if you want to have anything changed.

I don't think I can push this release to CocoaPods. @gfontenot perhaps? (You're listed as a maintainer https://cocoapods.org/pods/Result.)

**Comment by gfontenot** [comment]
on it. Happy to add you as a maintainer in CP as well. Just let me know which address to send it to.

**Comment by robrix** [comment]
:+1: Thank _you_ @Thomvis! I’m deeply indebted to each of the various contributors who’ve submitted PRs, added tags, reviewed code, filed issues, and otherwise helped out.

**Comment by Thomvis** [comment]
@gfontenot sent you an email!

**Comment by gfontenot** [comment]
Added you as a maintainer, but it looks like CocoaPods (0.37) is crashing while trying to validate the pod. Feel free to push if you can figure that out.

**Comment by Thomvis** [comment]
I also encountered that crash when working on a different pod. Probably [this issue](https://github.com/CocoaPods/CocoaPods/issues/3748)?

Do you host the podspec somewhere, or should I just grab it from the specs repo, update it and push it again?

**Comment by gfontenot** [comment]
I just grabbed the JSON version from the specs repo and have been updating that.

**Comment by Thomvis** [comment]
I was able to push a new version of the spec using the latest beta version of CocoaPods! See https://cocoapods.org/pods/Result
