### ISSUE TITLE
Carthage error: Scheme Result-watchOS is not currently configured for the build action.

### ISSUE THREAD

**Issue by justinmakaila** [antitypical/Result#71]
When I open the `xcodeproj`, Result-watchOS shows up in the schemes list with a cog next to it.

Using 0.5

**Comment by sync** [comment]
I think if you update carthage to 0.7.5 issue will go away, see #65

**Comment by justinmakaila** [comment]
@sync I don't think the issues are related. I'm on `0.7.5`

**Comment by robrix** [comment]
Thanks for filing!

> Result-watchOS shows up in the schemes list with a cog next to it.

I’m not sure what this means?

It doesn’t build the watchOS target when I bootstrap a project with it, so that’s curious.

**Comment by justinmakaila** [comment]
@robrix In the Xcode project, next to the scheme, it shows a little cog for the watchOS target. If I remove this from the shared schemes, I can build it just fine.

**Comment by JaviSoto** [comment]
Hi @justinmakaila, can you perhaps share a screenshot? I'm not sure where the issue lies. Does it fail to build from Carthage? From Xcode? What version of Xcode are you using?

**Comment by rpowelll** [comment]
I'm running into this issue as well. I created a _Cartfile_ with the following contents:

```
github "antitypical/Result" "0.6-beta.1"
```

Running `carthage update` with that Cartfile produces the following output:

```
$ carthage update
*** Fetching Result
*** Checking out Result at "932ac1aabf6d881ead74c4e6911d1271e95d2859"
*** xcodebuild output can be found in /var/folders/mn/xfk73_v56ns232tl5s448zdm0000gn/T/carthage-xcodebuild.sikNM2.log
*** Building scheme "Result-iOS" in Result.xcodeproj
*** Building scheme "Result-Mac" in Result.xcodeproj
*** Building scheme "Result-watchOS" in Result.xcodeproj
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
A shell task failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
```

Some environment details:

- **OS X Version** 10.10.4 (14E46)
-  **Xcode Version** 7.0 beta 4 (7A165t)
- **Carthage Version** 0.7.5

Interestingly, if I open `Result.xcodeproj` and try to build the _Result-watchOS_ scheme from there, it works without a hitch, making me wonder if this is a Carthage issue.

**Comment by rpowelll** [comment]
Some more potentially helpful information. If I try to run unit tests against the watchOS target, I get an error: _No such module 'XCTest'_

**Comment by robrix** [comment]
Sounding more and more like a Carthage issue to me, alas.

**Comment by neilpa** [comment]
> If I try to run unit tests against the watchOS target, I get an error: No such module 'XCTest'

Unit tests currently don't work for watchOS targets - https://openradar.appspot.com/21760513

**Comment by rpowelll** [comment]
I just tried this under 10.11 with Xcode beta 3 and it works fine, I'm going to try upgrading to beta 4 and seeing if that causes this issue to pop up again.

**Comment by rpowelll** [comment]
Okay it works fine with Xcode 7b4 under OS X 10.11.

**Comment by gfontenot** [comment]
Is this still an issue?

**Comment by Thomvis** [comment]
I've not seen this issue when building Result for watchOS on the GM. I'd say it is safe to close this one.

**Comment by guidomb** [comment]
This is still happening.

```
carthage bootstrap --platform ios
*** Downloading Box.framework binary at "1.2.2"
*** Checking out WLXBluetoothDevice at "0.2.0"
*** Checking out Result at "0.4.4"
*** Downloading ReactiveCocoa.framework binary at "v3.0"
*** Checking out expecta at "v1.0.3"
*** Checking out specta at "v1.0.3"
*** Checking out CocoaLumberjack at "2.0.1"
*** xcodebuild output can be found in /var/folders/gf/dslbq4t94zg44sz7wnk2lg2r0000gp/T/carthage-xcodebuild.XeyuaP.log
*** Building scheme "CocoaLumberjackSwift" in Lumberjack.xcodeproj
A shell task failed with exit code 66:
xcodebuild: error: Scheme Result-watchOS is not currently configured for the build action.
```

**Cartfile.resolved**

```
github "robrix/Box" "1.2.2"
github "CocoaLumberjack/CocoaLumberjack" "2.0.1"
github "specta/expecta" "v1.0.3"
github "specta/specta" "v1.0.3"
github "antitypical/Result" "0.4.4"
github "ReactiveCocoa/ReactiveCocoa" "v3.0.0"
github "Wolox/WLXBluetoothDevice" "0.2.0"
```

I am using carthage `0.9.2`. As @robrix said, I think this is an issue in Carthage because the same happens to me randomly with CocoaLumberjack.

**Comment by guidomb** [comment]
```
xcodebuild -version
Xcode 6.4
Build version 6E35b
```
