### ISSUE TITLE
Type 'ErrorType' does not confirm to protocol 'ErrorType'

### ISSUE THREAD

**Issue by charlag** [antitypical/Result#72]
I don't know if it's Swift bug, but I cannot use Result in Swift 2.0 (Xcode 7 beta 3, Result 0.6-beta1)

**Comment by charlag** [comment]
Note: using custom enum like
`enum StrangeErr: ErrorType { }`
and using it as param in generic works. Inheriting classes, protocols or structs from ErrorType does not work. I think it's Swift problem.

**Comment by charlag** [comment]
It looks like ErrorType cannot be inherited or instantiated (providing type in enum does not inherit, but specify raw type). I apologize.

**Comment by charlag** [comment]
`Result<T, Error: ErrorType>` cannot be right, because ErrorType cannot be inherited or instantiated.

**Comment by charlag** [comment]
But it can be used as enum raw type, sorry again.

**Comment by kareman** [comment]
@charlag 
You can instantiate types conforming to ErrorType as long as they includes these 2 properties:

```swift
public let _domain: String = "FootlessParser.ParserError"
public let _code: Int = 1
```

See https://github.com/kareman/FootlessParser/blob/Swift2.0/source/Parser.swift for an example.
