### ISSUE TITLE
Failed to install via Carthage

### ISSUE THREAD

**Issue by ReDetection** [antitypical/Result#74]
My Cartfile
```
github "ReactiveCocoa/ReactiveCocoa" "v3.0-RC.1"
```
Unfortunately, `carthage update` gives this output:
```
$ carthage update
*** Fetching ReactiveCocoa
*** Fetching Result
*** Fetching Box
*** Checking out Result at "0.4.4"
*** Downloading Box at "1.2.2"
*** Downloading ReactiveCocoa at "v3.0 Release Candidate 1"
*** xcodebuild output can be found in /var/folders/jk/0zp2_vl57vz661xk_hm5klxr0000gp/T/carthage-xcodebuild.qWDqGQ.log
Failed to discover shared schemes in project Result.xcodeproj—either the project does not have any shared schemes, or xcodebuild never returned

If you believe this to be a project configuration error, please file an issue with the maintainers at https://github.com/antitypical/Result/issues/new
```
xcodebuild log is empty. 
P.S. It's unclear who is to blame but let's start investigation from here. Can you please help me?

**Comment by ikesyo** [comment]
I can't reproduce it. Is there any change if you remove the cache from `~/Library/Caches/org.carthage.CarthageKit/dependencies/Result`?

**Comment by ReDetection** [comment]
well, even after `rm -rf ~/Library/Caches/org.carthage.CarthageKit/dependencies/` output was similar 
```
$ carthage update
*** Cloning ReactiveCocoa
*** Cloning Result
*** Cloning Box
*** Checking out Result at "0.4.4"
*** Downloading Box at "1.2.2"
*** Downloading ReactiveCocoa at "v3.0 Release Candidate 1"
*** xcodebuild output can be found in /var/folders/jk/0zp2_vl57vz661xk_hm5klxr0000gp/T/carthage-xcodebuild.p5xKlN.log
Failed to discover shared schemes in project Result.xcodeproj—either the project does not have any shared schemes, or xcodebuild never returned

If you believe this to be a project configuration error, please file an issue with the maintainers at https://github.com/antitypical/Result/issues/new
```
I find it very strange Carthage builds ReactiveCocoa before Result. Well, I'm not sure it succeeds with ReactiveCocoa, but in the `build` folder there are both `Box.framework` and `ReactiveCocoa.framework`, and Result workspace are still in `checkout` dir. Oh, look, error message complains about `xcodeproj` while you have a `xcworkspace`. I know, schemes are in `xcodeproj` anyway, but maybe it's an issue?

I'm running Yosemite, default Xcode version is 6.4, Carthage version 0.8. 
Should I file an issue to the Carthage repo?

**Comment by ReDetection** [comment]
Removing the `binaries` folder helped. Thanks @ikesyo. 
`rm -rf ~/Library/Caches/org.carthage.CarthageKit/binaries/`

**Comment by robrix** [comment]
Thanks @ikesyo! :yellow_heart:
