### ISSUE TITLE
how to handle Result<nil, nil> ?

### ISSUE THREAD

**Issue by connectdotz** [antitypical/Result#75]
How to handle the use case when both result value and error are nil...  For example when querying db yielding no result, it is not an error but we have nothing to return either. I know we can return an empty array to work around this issue, but seems like there should be a more elegant and clean solution...??

**Comment by neilpa** [comment]
An empty array is perfectly reasonable for the result if your query returns a collection of values. If it's a scalar that's optional, define it as such, e.g. `Result<Int?, SomeError>`

**Comment by connectdotz** [comment]
tried that, but here is the weird result:

```
enum Whatever: ErrorType {
    case e1, e2
}

func test1() -> Result<String?, Whatever> {
    return .Success(nil)
}

if let s = test1().value {
    print("s should not be nil: \(s)")
} else {
    print("s is nil")
}
```
and we got:
```
s should not be nil: nil
```

**Comment by neilpa** [comment]
That's because `value` returns `T?` which means `String??` if you plug in your types. The `if-let` unwraps the outer optional of the returned `Some(nil)`, hence printing nil.

**Comment by connectdotz** [comment]
Sure, but the question remain that how do we elegantly retrieve the actual value without verbose workaround

```
if let s1 = test1().value, s = s1 ...

if let s = (test1().value ?? nil) ...
```
Is there a better way to do this double-optional unwrapping? Can the value property unwrap the optional value before returning? Ideally ` if let s = test1.value` should work for either `Result<String,Error>` or `Result<String?,Error>`...

**Comment by neilpa** [comment]
I wouldn't call it a "verbose workaround", that's just what you have to do if you have nested optionals. If you're using Swift 2 you could pattern match over the result and avoid `value` entirely. (This doesn't work as well in Swift 1.2 due to the need for `Box`).

**Comment by ahernandezlopez** [comment]
Have you tried `Result<Void, MyErrorType>`?

    enum MyErrorType: ErrorType {
        case None
    }

I was wondering kind of the same some weeks ago @ http://stackoverflow.com/questions/30875889/implement-an-equatable-void-none-type/33142599#33142599 :-)

**Comment by ikesyo** [comment]
You can write the case as follows in Swift 2:

```swift
if case let s?? = test1().value {
    print("s should not be nil: \(s)")
} else {
    print("s is nil")
}
```

**Comment by gfontenot** [comment]
I'm going to go ahead and close this. If it's still an issue or if these solutions don't work for you, feel free to re-open.
