### ISSUE TITLE
Could 'Error' generic parameter be removed?

### ISSUE THREAD

**Issue by damienrambout** [antitypical/Result#76]
Hi,

I was planning to use Result for my internal framework that access to a remote API and defines model types with convenience functions to access that API. (e.g: `user.fetchFriends()`).
This would give something like that: `User.fetchFriends()` -> `API.fetchFriends()` -> `Alamofire.request(.GET, ...)` -> `NSURLSession`...

However, the `Error` generic parameter requires to define a specific `ErrorType` for the `Result` objects. In my case, an API call could result into several kinds of error:
- The request was cancelled or timed out (`NSError`)
- HTTP error (`4xx` or `5xx`) (Could be `NSError` or could be an enum in my `API` class for standard HTTP errors)
- JSON validation error (could be an `ErrorType` enum defined in my `User` class for instance)

My point is, I will have errors returned by `NSURLSession` (cancelled, no internet connection, ...), my `API` class (http error), my model classes (JSON Validation, form validation, ...) and they won't be of the same kind (type). All these errors will be of `ErrorType`, but they won't share the same type.

To be able to use `Result<T>`, I would have to add an "underlying error" mechanism that would wrap the error coming from the previous step (e.g. `APIError` would wrap `NSError` objects returned by `NSURLSession` and then `User.Error` would have a case like `case API(error: APIError)` to wrap api errors, and so on).

I can understand that `Result<T, Error: ErrorType>` will force some kind of automatic documentation about the kind of error returned, but this is restrictive as well. `Result<T>` would be fine as well and let the developer decide whether all errors should be of the same type. After all, the whole `do { try } catch { }` mechanism has been designed to handled several error types using multiple `catch` statements (and these errors are not specified in the called function signature).

I know this would have a huge impact on the current implementation, but it's worth talking about it.

**Comment by JaviSoto** [comment]
That is a great question, sir :)

This is how I deal with this particular issue, in my networking APIs. I create a error type that can encapsulate each of those. That way, it's also easier for the clients of this API to know which *kind* of error was encountered.

Example:

```swift
enum MyAPIErrorType: ErrorType {
    case JSONParsingError(NSError)
    case NetworkingError(NSError)
    case SomeOtherSpecificError(AssociatedErrorType)
```

So your APIs will return `Result<XYZ, MyAPIErrorType>`, and in the implementation you have to make sure you *catch* each different type of error and wrap it with the appropriate `MyAPIErrorType` case.

How does this sound? :)

**Comment by robrix** [comment]
Some historical context: The decision to parameterize `Result` by an `Error` was the result of [a long discussion on LlamaKit](https://github.com/LlamaKit/LlamaKit/issues/10) (of which this framework is the spiritual successor).

@JaviSoto’s suggestion is the recommended path :+1:

**Comment by damienrambout** [comment]
@JaviSoto @robrix You are absolutely right that errors should be wrapped by each layer.
It's sometimes easier to just forward the error without defining a new one... :-) Or defining global errors such as `NoInternetConnection` or `RequestTimedOut`. 

Ok thanks, I'll wrap more then :-)
