### ISSUE TITLE
Rename Result module name to handle namecollisions better

### ISSUE THREAD

**Issue by tmu** [antitypical/Result#84]
Name `Result` is very common in different libraries (e.g. old BrightFuture had its own result, Alamofire has Result, my own code had Result enum). It would make it easier to handle name collision if the name of the Result module would be different. Due to implicit namespace importing, Swift 2 compiler gets confused of the following 

```
     import Alamofire // implicitly exposes Result enum (Alamofire.Result)
     import Result // implicitly exposes Result enum (Result.Result)

     func foo() -> Result.Result<NSData, NSError> { ... } // compiler thinks the Result before dot refers to implictly exposed enums, not to the module
````

**Comment by gfontenot** [comment]
This is really a problem with the swift compiler. I believe there are a number of bugs tracking it. There was a workaround discussed in #77.

**Comment by robrix** [comment]
If we wanted, we could build this workaround into Result.framework. I (facetiously) suggest calling it `ComAntitypicalResult` :stuck_out_tongue_closed_eyes:

@antitypical/result: Triage: should we deal with this for 1.0?

**Comment by mdiep** [comment]
I'd suggest someone open a PR against Alamofire to use this `Result`. :smile:

I don't think we should do anything about this.

**Comment by neilpa** [comment]
> I don't think we should do anything about this.

Agreed

**Comment by neilpa** [comment]
Given that this is the de facto standard, the other libs should either consume it or rename their clones.

**Comment by robrix** [comment]
Okay. Closing.

**Comment by SebastianBoldt** [comment]
Same Problem over here? Any Suggestions how to fix this? Manually renaming the Product Module Name is not possible when using Cocoapods.

**Comment by mdiep** [comment]
```swift
import enum Result.Result
```
