### ISSUE TITLE
Remove `try`

### ISSUE THREAD

**Issue by neilpa** [antitypical/Result#85]
Now that Cocoa APIs map to `throws` we should be able to remove these and rely entirely on `materialize`.

**Comment by neilpa** [comment]
Although, it may be interesting to explore repurposing these for C-APIs returning error codes and out-params.

**Comment by robrix** [comment]
Those can be done orthogonally. :+1: to both.

**Comment by neilpa** [comment]
Opened #87 for the C wrappers
