### ISSUE TITLE
Box dependency should be frozen

### ISSUE THREAD

**Issue by guidomb** [antitypical/Result#90]
In version `0.4.4` this`github "robrix/Box"` should be changed to `github "robrix/Box" ~> 1.2.2`. Because if not proyects including result (using Swift 1.2) should explicity add `Box` to their `Cartfile` because the latest version of box is not compatible with Swift 1.2

**Comment by gfontenot** [comment]
The newest release of Box is 2.0.0, which won't be compatible with a version constraint of `~> 1.2.2`, so I don't think this is an actual issue.

**Comment by guidomb** [comment]
Well the issue is that Box `2.0.0` is not compatible with Swift 1.2. People still using Swift 1.2 and Result `0.4.4` will start seing failures when they execute `carthage update` because Box will be updated to the latest version. The only way to avoid a failure is to specify the version of Box in your Cartfile but for me that does not right. Users of Result should not experience herratic behavior. As a user if you are not updating Result you should not experience a failure caused by Result's dependencies. As far as I know Result `0.4.4` only works with Swift 1.x so all its dependencies should also be Swift 1.x compatible.

**Comment by gfontenot** [comment]
Oh, I see. I misread your initial post. Yes, there should be a version constraint on `Box` for earlier versions. We should probably release `0.4.5` to handle this.

**Comment by guidomb** [comment]
:+1:

**Comment by ikesyo** [comment]
This is addressed by #99 and I've just cut a new release: [0.4.5](https://github.com/antitypical/Result/releases/tag/0.4.5).

**Comment by robrix** [comment]
:bow: thanks all :heart:
